@startuml

class Person {
}

class Member {
}

class BoardMember {
}

class Event {
}

class Conference {
}

class BoardMeeting {
}

class Location {
}

class AAUOC {
}

 Member --> Person
 BoardMember --> Member

 Conference --> Event
 BoardMeeting --> Event



@enduml